language: python
python:
  - "3.7"

dist: bionic

# command to install dependencies
install:
  - sudo apt-get update
  - pip install chardet==3.0.4
  - python setup.py install
  - pip install coveralls
  - pip install pathos
  - pip install numpy
  - pip install pandas
  - pip install scipy
  - python -m spacy download en_core_web_sm
  - pip install dill
  - pip install nltk
  - pip install spacy
  - pip install gensim==3.8.3
  - pip install pytest
  - pip install progressbar2
  - pip install wheel
  - pip install twine
  - python -c "import nltk; nltk.download('punkt'); nltk.download('wordnet')"
  - python -c "from seaqube import download;download('vec4ir')"
  - python -c "import vec4ir;  a=vec4ir.utils.Counter(['a','word']); print(a)" # does it work now?
  - pip install torch==1.7.1+cpu torchvision==0.8.2+cpu torchaudio==0.7.2 -f https://download.pytorch.org/whl/torch_stable.html

# deploy:
# python setup.py sdist bdist_wheel
# twine upload --repository testpypi dist/*
# twine upload --repository pypi dist/*
# for dist, prepare first this file here: https://truveris.github.io/articles/configuring-pypirc/

script:
  - py.test  tests/test_*  -v
  - pip uninstall seaqube -y
#after_success:
#  - coveralls