language: python
python:
  - "3.7"

dist: bionic

# command to install dependencies
install:
  - sudo apt-get update
  - python setup.py install
  - pip install coveralls
  - pip install pathos
  - pip install numpy
  - pip install pandas
  - pip install scipy
  - python -m spacy download en_core_web_sm
  - pip install dill
  - pip install nltk
  - pip install spacy
  - pip install gensim
  - pip install pytest
  - pip install progressbar2
  - pip install wheel
  - pip install twine
  - python -c "import nltk; nltk.download('punkt')"

# deploy:
# python setup.py sdist bdist_wheel
# twine upload --repository testpypi dist/*
# twine upload --repository pypi dist/*
# for dist, prepare first this file here: https://truveris.github.io/articles/configuring-pypirc/

script:
  - py.test  tests/test_* 
  - pip uninstall seaqube -y
#after_success:
#  - coveralls